#!/bin/sh
alias f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	vim="$EDITOR" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	lsp="yay -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	rem="yay -Rns" \
	clean="yay -Rns $(yay -Qtdq) ;sudo paccache -rk1" \
	ls="exa -l -h --group-directories-first -s name --color=always" \
	la="exa -a -l -h --group-directories-first -s name --color=always" \
	upload="aws s3 cp" \
	refresh="killall -q dwmblocks;setsid dwmblocks &"

